# Generated by Django 5.2.1 on 2025-05-13 06:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_savechas_delete_admin_delete_barber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savechas',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='savechas',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
