# Generated by Django 5.2.1 on 2025-05-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_savechas_date_alter_savechas_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
